const { execSync } = require('child_process');

const issues = [
  { title: '[Test] Add Jest Unit Tests for FileBrowser Component', body: 'The `FileBrowser.tsx` component handles the core file navigation logic. We need basic rendering and click event unit tests using Jest and React Testing Library.', labels: 'good first issue, testing' },
  { title: '[Test] Add Jest Unit Tests for GenerateNotesModal', body: 'Add unit tests to ensure the modal opens, closes, and correctly fires the generate callback.', labels: 'good first issue, testing' },
  { title: '[A11y] Add ARIA labels to all icon buttons', body: 'Many of our icon-only buttons lack proper `aria-label` attributes, making them inaccessible to screen readers. Please audit the `src/components` folder and add them.', labels: 'good first issue, accessibility' },
  { title: '[UI] Add Loading Skeletons for FileRow', body: 'When files are fetching, the screen is blank. Implement a shimmer/loading skeleton version of `FileRow.tsx` to show while data is loading via SWR.', labels: 'good first issue, frontend' },
  { title: '[Feature] Add "Copy to Clipboard" button in AI Notes', body: 'Add a small floating "Copy" button in the corner of generated AI Markdown notes so users can easily copy the text.', labels: 'good first issue, enhancement' },
  { title: '[Feature] Add Syntax Highlighting to Markdown Renderer', body: 'We use `react-markdown`. Add the `rehype-highlight` or `prismjs` plugin so any code blocks generated by the AI have syntax highlighting.', labels: 'good first issue, frontend' },
  { title: '[SEO] Add dynamic OpenGraph tags to study pages', body: 'Update `src/app/layout.tsx` or page files to generate dynamic `og:title` and `og:image` tags so when students share links on WhatsApp, a nice preview appears.', labels: 'good first issue, seo' },
  { title: '[Performance] Lazy Load Heavy React Components', body: 'Use `next/dynamic` to lazy load modals (like `GenerateNotesModal`) so they don\'t block the initial page load bundle.', labels: 'good first issue, performance' },
  { title: '[Feature] Add Keyboard Shortcuts (Ctrl+K to Search)', body: 'Implement a global event listener that focuses the search bar when the user presses `Cmd+K` or `Ctrl+K`.', labels: 'good first issue, enhancement' },
  { title: '[UI] Implement Toast Notifications for API Errors', body: 'Replace native `alert()` calls in the Profile and API routes with a beautiful Toast notification library like `react-hot-toast` or `sonner`.', labels: 'good first issue, frontend' },
  { title: '[Refactor] Extract CSS into standard CSS Modules', body: 'Some components use inline styles. Move these into proper `.module.css` files for better maintainability.', labels: 'good first issue, refactor' },
  { title: '[Feature] Add "Scroll to Top" floating button', body: 'When browsing long lists of PDFs, a "Scroll to Top" button should appear in the bottom right corner when scrolled past 500px.', labels: 'good first issue, frontend' },
  { title: '[A11y] Ensure color contrast ratios meet WCAG AA standards', body: 'Audit the colors in `globals.css` and ensure text on background colors has at least a 4.5:1 contrast ratio.', labels: 'good first issue, accessibility' },
  { title: '[Feature] Implement standard 404 Not Found Page', body: 'Create a custom `src/app/not-found.tsx` with a fun, educational-themed 404 graphic and a button to return home.', labels: 'good first issue, frontend' },
  { title: '[Feature] Add standard 500 Error Boundary Page', body: 'Create a custom `src/app/error.tsx` to catch and display client-side crashes gracefully instead of a blank white screen.', labels: 'good first issue, frontend' },
  { title: '[Enhancement] Add hover tooltip for long file names', body: 'If a PDF file name is truncated with ellipsis, show the full name in a tooltip when hovering over the row.', labels: 'good first issue, frontend' },
  { title: '[Feature] Allow sorting files by Date or Name', body: 'Add a simple dropdown in the FileBrowser to sort the visible files alphabetically or by newest first.', labels: 'good first issue, enhancement' },
  { title: '[Docs] Improve README.md with screenshots', body: 'Our repository needs visual appeal. Add high-quality screenshots of the app (Dashboard, AI Notes, 1-Pager) to the `README.md`.', labels: 'good first issue, documentation' },
  { title: '[Docs] Add Architecture Diagram to CONTRIBUTING.md', body: 'Create a simple Mermaid.js diagram in the contributing file to explain how the Next.js frontend talks to the Gemini API backend.', labels: 'good first issue, documentation' },
  { title: '[Enhancement] Cache AI generated responses in LocalStorage', body: 'If a user requests the same topic note twice in one session, check `localStorage` before burning an API call.', labels: 'good first issue, frontend' },
  { title: '[PWA] Add manifest.json for Progressive Web App', body: 'Add a `manifest.json` and meta tags so students can "Install to Home Screen" on Android and iOS.', labels: 'good first issue, enhancement' },
  { title: '[PWA] Add offline fallback page', body: 'Configure a basic service worker to show a custom "You are offline" page when a student loses internet on campus.', labels: 'good first issue, enhancement' },
  { title: '[i18n] Add Hindi Language Support framework', body: 'Set up `next-intl` or a basic Context to allow toggling the UI text between English and Hindi.', labels: 'good first issue, enhancement' },
  { title: '[Refactor] Type strongly all API responses', body: 'Replace `any` types in `src/app/api/...` with proper TypeScript interfaces for better type safety.', labels: 'good first issue, typescript' },
  { title: '[Test] Add E2E tests for Authentication flow', body: 'Write a basic Playwright or Cypress test that verifies the Sign In page renders correctly and redirects to GitHub/Google.', labels: 'good first issue, testing' },
  { title: '[UI] Add empty state graphics for empty folders', body: 'When a folder has no PDFs, show a friendly illustration (SVG) instead of just an empty list.', labels: 'good first issue, frontend' },
  { title: '[Security] Add rate limiting indicator to UI', body: 'If the API returns a 429 Too Many Requests, show a visual countdown timer until they can try again.', labels: 'good first issue, frontend' },
  { title: '[Feature] Add "Share Note" button with Web Share API', body: 'Use `navigator.share()` on mobile devices to let students easily WhatsApp a generated note to their friends.', labels: 'good first issue, enhancement' },
  { title: '[UI] Add subtle entry animations for lists', body: 'When navigating folders, animate the file rows sliding in slightly using CSS animations or Framer Motion.', labels: 'good first issue, frontend' },
  { title: '[Feature] Add "Report Issue" button on generated notes', body: 'If the AI generates a wrong formula, users need a way to flag it. Add a simple mailto link or form to report bad generations.', labels: 'good first issue, enhancement' },
  { title: '[Test] Fix React hydration warnings', body: 'Check the browser console in development mode for hydration mismatch warnings and fix the underlying HTML issues.', labels: 'good first issue, frontend' },
  { title: '[SEO] Create an automatic dynamic sitemap route', body: 'Update the `sitemap.xml` generation to dynamically list all major university folders if possible.', labels: 'good first issue, seo' },
  { title: '[Enhancement] Format dates relatively (e.g., "2 days ago")', body: 'Use `date-fns` or native `Intl.RelativeTimeFormat` to display file upload dates relatively rather than strict timestamps.', labels: 'good first issue, frontend' },
  { title: '[Enhancement] Add PDF file size to UI', body: 'If the API provides the file size, format it nicely (e.g., "2.4 MB") and display it in the FileRow.', labels: 'good first issue, frontend' },
  { title: '[UI] Highlight current folder path in breadcrumbs', body: 'Make the current active folder in the breadcrumb navigation bold and a different color to improve orientation.', labels: 'good first issue, ui/ux' },
  { title: '[Performance] Preconnect to critical third-party domains', body: 'Add `<link rel="preconnect">` tags to `layout.tsx` for Google Fonts and GitHub avatar CDNs to speed up load times.', labels: 'good first issue, performance' },
  { title: '[Enhancement] Add confirmation modal before Account Deletion', body: 'The current profile page uses `alert()`. Replace this with a proper React modal overlay for account deletion.', labels: 'good first issue, frontend' },
  { title: '[Docs] Create an Issue Template', body: 'Add `.github/ISSUE_TEMPLATE/bug_report.md` and `feature_request.md` to standardize how community members report bugs.', labels: 'good first issue, documentation' },
  { title: '[Docs] Create a Pull Request Template', body: 'Add `.github/PULL_REQUEST_TEMPLATE.md` to remind contributors to check their formatting before submitting code.', labels: 'good first issue, documentation' },
  { title: '[Enhancement] Make the 1-Pager generation badge clickable', body: 'The "ONE PAGE REVISION" badge in the Satori template should ideally link back to the repo or website when shared as an image.', labels: 'good first issue, enhancement' },
  { title: '[Security] Sanitize Markdown output', body: 'Ensure that the AI generated markdown is run through a sanitizer like `DOMPurify` to prevent XSS attacks.', labels: 'good first issue, security' },
  { title: '[Refactor] Remove unused dependencies from package.json', body: 'Audit the `package.json` for libraries we are no longer using and remove them to shrink the `node_modules` size.', labels: 'good first issue, refactor' },
  { title: '[Feature] Add "Recently Viewed" section to dashboard', body: 'Track the last 5 viewed files in LocalStorage and display them as quick links on the home page.', labels: 'good first issue, enhancement' },
  { title: '[A11y] Ensure all inputs have associated labels', body: 'Form inputs in the profile page lack proper `<label htmlFor="...">` associations. Fix this for screen readers.', labels: 'good first issue, accessibility' },
  { title: '[Enhancement] Auto-resize textarea for AI Prompts', body: 'If we add custom AI prompting in the future, ensure the `<textarea>` automatically expands its height based on content.', labels: 'good first issue, frontend' },
  { title: '[UI] Add a custom scrollbar design', body: 'The default browser scrollbar is ugly on Windows. Add webkit CSS rules to make the scrollbar slim, rounded, and match the app theme.', labels: 'good first issue, frontend' },
  { title: '[Feature] Allow toggling between Grid and List view', body: 'Add a toggle in the FileBrowser to switch from standard list view to a tile/grid view for PDFs.', labels: 'good first issue, enhancement' },
  { title: '[Performance] Optimize heavy SVGs', body: 'Run any raw SVG icons in the codebase through SVGOMG to strip unnecessary metadata and reduce bundle size.', labels: 'good first issue, performance' },
  { title: '[Test] Add basic CI/CD GitHub Actions workflow', body: 'Create a `.github/workflows/ci.yml` file that runs `npm install` and `npm run build` on every PR to catch broken code early.', labels: 'good first issue, devops' },
  { title: '[Feature] Add "Confetti" on successful Account Link', body: 'When a user successfully links their GitHub account for contribution credits, fire off a `react-confetti` animation to celebrate!', labels: 'good first issue, ui/ux' }
];

console.log(`Starting to create ${issues.length} issues...`);

for (let i = 0; i < issues.length; i++) {
  const issue = issues[i];
  try {
    // Escape quotes for bash execution
    const title = issue.title.replace(/"/g, '\\"');
    const body = issue.body.replace(/"/g, '\\"');
    
    // Some labels like accessibility, testing might not exist, so we fall back to just "good first issue"
    // To be safe and not fail like earlier, we will just use 'good first issue' and 'enhancement' for all of them
    const command = `gh issue create --title "${title}" --body "${body}" --label "good first issue" --label "enhancement"`;
    
    console.log(`Creating issue ${i + 1}/${issues.length}: ${title}`);
    execSync(command, { stdio: 'ignore' });
    
    // Sleep for 2.5 seconds to avoid GitHub API abuse rate limits
    execSync('sleep 2.5');
  } catch (error) {
    console.error(`Failed to create issue: ${issue.title}`);
  }
}

console.log("Successfully created 50 Good First Issues!");
